name: PR Check

on: [pull_request]

jobs:
  generate:
    name: Lint Rego
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Regal
        uses: StyraInc/setup-regal@main
        with:
          version: 'latest'

      - name: Lint
        run: |
          regal lint policy/ --format=github
